# -*- coding: utf-8 -*-
"""MLOPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydrp3cYEHWJ2Ot3MLgNEJHzicCP0_gcf
"""


import json
import warnings

import joblib
import mlflow
import mlflow.sklearn
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from xgboost import XGBRegressor
#from sklearn.metrics import mean_square
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from math import*
from matplotlib import pyplot as plt
import seaborn as sns
warnings.filterwarnings("ignore")

from sklearn.datasets import fetch_california_housing
X,y=fetch_california_housing(return_X_y=True,as_frame=True)
X_0,X_test,y_0,y_test=train_test_split(X,y,test_size=0.1,random_state=42)
X_train,X_val,y_train,y_val=train_test_split(X_0,y_0,test_size=0.2,random_state=42)



print(y_train)

print(f"les dimmension de X_train sont {X_train.shape}")
print(f"les dimmension de y_train sont {y_train.shape}")

X.info()

"""## Analyse descriptive"""


cols=X.columns
plt.figure(figsize=(15,12))
for col in enumerate(cols,1):
  plt.subplot(3,3,col[0])
  sns.histplot(X[col[1]],kde=True)
plt.show()

sns.histplot(y,kde=True)

# SCALING
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)  # transform seulement, pas fit

joblib.dump(scaler, "scaler.joblib")

# MODÈLES
models = {
    "RandomForest": RandomForestRegressor(
        n_estimators=300,
        max_depth=7,
        random_state=42,
        n_jobs=-1,
    ),

    "XGBoost":XGBRegressor(
        n_estimators=500,
        max_depth=7,
        learning_rate=0.03,
        random_state=42,
        n_jobs=-1,
        early_stopping_rounds=50,),
}

"""## Entrainement avec MLFLOW"""


# ENTRAÎNEMENT AVEC MLFLOW
mlflow.set_tracking_uri("sqlite:///mlflow.db")
mlflow.set_experiment(experiment_name="california_housing")
best_r2=0
best_model_name=None
for model_name, model in models.items():
    with mlflow.start_run():
        # Si c'est XGBoost, on fournit le eval_set requis pour l'early stopping
        if model_name == "XGBoost":
            model.fit(X_train_scaled, y_train, eval_set=[(X_val_scaled, y_val)], verbose=False)
        else:
            model.fit(X_train_scaled, y_train)

        y_pred = model.predict(X_val_scaled)
        metrics = {"mse":mean_squared_error(y_val, y_pred),
                   "rmse":sqrt(mean_squared_error(y_val, y_pred)),
                   "mae":mean_absolute_error(y_val, y_pred),
                   "r2":r2_score(y_val, y_pred)}
        mlflow.log_metrics(metrics)
        mlflow.log_params(model.get_params())
        if model_name=="XGBoost":
          mlflow.xgboost.log_model(model, model_name)
        else:
          # On autorise explicitement les types d'arbres de scikit-learn pour skops
          mlflow.sklearn.log_model(
              model,
              model_name,
              skops_trusted_types=["sklearn.tree._tree.Tree"]
          )

        mlflow.set_tag("model_type", model_name)

        print(f"\n{'='*50}")
        print(f"{model_name}")
        for metric_name, value in metrics.items():
            print(f"{metric_name}: {value:.4f}")
        if metrics["r2"]>best_r2:
          best_r2=metrics["r2"]
          best_model_name=model_name
          joblib.dump(model,"best_model.joblib")


print(f"\n{'='*50}")
print(f"Meilleur modèle : {best_model_name} (R2 = {best_r2:.4f})")
with open("best_model_name.txt","w") as f:
  f.write(best_model_name)

import csv
X_test.to_csv('X_test.csv', index=False)
y_test.to_csv('y_test.csv', index=False)
features_names = X_test.columns.tolist()
with open("features_names.txt", "w") as f:
    f.write(",".join(features_names))

",".join(features_names)

print(features_names)